### ISSUE TITLE
[Bug] Can't set status on certain songs

### ISSUE THREAD

**Issue by HoughIO** [cheshire137/spotify-slack-status#3]
When listening to this song:
https://open.spotify.com/track/6xKQQTR4pQVAKok4J4lzMt

`Death Grips - You Might Think He Loves You For Your Money But I Know What He Really Loves You For It's Your Brand New Leopard Skin Pillbox Hat`

I cannot update my slack status.

This is probably because of how long the song title is.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4359920/25092161/6fd05810-235a-11e7-845c-b837e43b4dfe.png)

Reproduction steps:
1) Listen to this song on spotify (https://open.spotify.com/track/6xKQQTR4pQVAKok4J4lzMt)
2) Try to set spotify status with the slash command, or through the app page.
3) See failure

- [ ] Fixed
- [ ] Verified

**Comment by cheshire137** [comment]
Oh interesting! I thought perhaps you were getting a different song in your status, like #2, but this is different. Will try it!

**Comment by HoughIO** [comment]
QA'd the shit out of it famo

**Comment by HoughIO** [comment]
Also, the output from slack looks like this:
![image](https://cloud.githubusercontent.com/assets/4359920/25104679/419a7c02-238f-11e7-9c0c-20cf733b8042.png)

Also, note that I have already signed in, the error from my first comment was trying to manually set it.

**Comment by cheshire137** [comment]
This is now fixed:

<img width="602" alt="slack_-_ex-mijos" src="https://cloud.githubusercontent.com/assets/82317/26027297/27480b5c-37d1-11e7-84f4-9259692b6866.png">

According to https://api.slack.com/methods/users.profile.set, the status can be at most 100 characters. Now the app checks for that first before trying to update your Slack status. Fixed in https://github.com/cheshire137/spotify-slack-status/commit/2a25792dd5ad853b1ee3efed9ec900176c467857.

**Comment by HoughIO** [comment]
Son I am a disappoint.
